# URL бота (HTTP API)
bot-api-url: "https://hiderealm-tg2fa-production.up.railway.app"

# Команда для сброса пароля (консольная команда)
# %player% - ник игрока, %password% - новый пароль
password-reset-command: "authme changepassword %player% %password%"

# Команда для смены пароля игроком (консольная)
# %player% - ник игрока, %password% - новый пароль
password-change-command: "authme changepassword %player% %password%"

# Время ожидания подтверждения входа (секунд)
login-timeout: 30

# ID сервера
server-id: "main"
